# Generated by Django 4.1.2 on 2022-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
