# Generated by Django 4.1.2 on 2022-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
