# Generated by Django 4.1.2 on 2022-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subscribedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
