# Generated by Django 4.1.2 on 2022-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_contactus_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='sex',
        ),
    ]
