# Generated by Django 4.1.2 on 2022-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_idcreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcreator',
            name='user_active',
            field=models.BooleanField(default=False),
        ),
    ]
