# Generated by Django 4.1.2 on 2022-11-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_idcreator_user_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idcreator',
        ),
    ]
