# Generated by Django 4.1.2 on 2023-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_subscribedusers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Password_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password_1', models.TextField(blank=True, max_length=500, null=True)),
                ('new_password_2', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'SetPassword',
                'verbose_name_plural': 'SetPassword',
            },
        ),
    ]
