# Generated by Django 4.1.2 on 2023-03-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_set_password_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set_Password_Form',
            new_name='Set_Password',
        ),
    ]
